Fixed issue #11 with correct absolute path import
import adafruit_fancyled as fancy

was causing a 
Traceback (most recent call last):
  File "code.py", line 21, in <module>
  File "/home/travis/build/adafruit/Adafruit_CircuitPython_Bundle/libraries/helpers/fancyled/adafruit_fancyled/fastled_helpers.py", line 111, in loadDynamicGradientPalette
AttributeError: 'module' object has no attribute 'CRGB'